
name: FrontEnd React CI

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'vite.config.*'
      - '.github/workflows/frontend-react-ci.yml'
      - 'package.json'
      - 'tsconfig*.json'
  pull_request:
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'vite.config.*'
      - '.github/workflows/frontend-react-ci.yml'
      - 'package.json'
      - 'tsconfig*.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint with ESLint
        run: |
          npx eslint "./src/**/*.{ts,tsx}" --max-warnings=0

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Build
        run: npm run build
